### ISSUE TITLE
getting some problem with ilqr_jax_MPC.py please can you help me to solve it !

### ISSUE THREAD

**Issue by Tanman1234** [ysgclight/Carla_iLQR_MPC#4]
D:\CARLA_0.9.5\PythonAPI\examples>py -3.7 ilqr_jax_MPC.py
pygame 2.0.1 (SDL 2.0.14, Python 3.7.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
call reset
  0%|                                                                                                                                                                                    | 0/2000 [00:00<?, ?it/s]WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
  0%|                                                                                                                                                                                    | 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "ilqr_jax_MPC.py", line 385, in <module>
    x_trj, u_trj, cost_trace = run_ilqr_main(state, u_trj, waypoints)
  File "ilqr_jax_MPC.py", line 292, in run_ilqr_main
    x_trj = rollout(x0, u_trj)
  File "ilqr_jax_MPC.py", line 99, in rollout
    return np.array((x0, x_trj,x_final))
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2859, in array
    out = stack([asarray(elt, dtype=dtype) for elt in object])
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2859, in <listcomp>
    out = stack([asarray(elt, dtype=dtype) for elt in object])
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2887, in asarray
    return array(a, dtype=dtype, copy=False, order=order)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2859, in array
    out = stack([asarray(elt, dtype=dtype) for elt in object])
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\jax\_src\numpy\lax_numpy.py", line 2671, in stack
    raise ValueError("All input arrays must have the same shape.")
jax._src.traceback_util.FilteredStackTrace: ValueError: All input arrays must have the same shape.

**Comment by YukunXia** [comment]
Hi, I'm not sure where does the `return np.array((x0, x_trj,x_final))` come from. I'm guessing you wanna vertically stack x0, x_trj,x_final together, which is actually a numpy problem. If so, you can use `np.vstack((x0, x_trj, x_final))`. Besides, I remember that in Jax, lax loop scanner already includes x_final in x_trj, or at least that should be the case when I was writing the program. In that case, you only need to return `np.vstack((x0, x_trj))` in the rollout function.

**Comment by Tanman1234** [comment]
yes but in this case also it giving same error 
when i tries to run this program as it is its giving same error

**Comment by YukunXia** [comment]
Could you provide a screenshot of your terminal, plus the environment you run on, eg. Jax version? Mentioning all the modifications you did will also help. Currently, I'm not sure how many changes you have made to the program.

**Comment by YukunXia** [comment]
Besides, it seems that the program couldn't be properly run on Windows at this point. The other programmer faced the issue with Jax version. Check this issue thread #3 .

**Comment by lzhhh93** [comment]
Hi @Tanman1234 @YukunXia, thanks for the discussion here and thank @YukunXia for the code.

I also have problem with jaxlib after install jax 0.1.68, specifically a ImportError: cannot import name 'pytree' from 'jaxlib'.
I am working on ubuntu 18.04.

Here is what i have done for installation of jax 0.1.68 by following https://github.com/google/jax/tree/jaxlib-v0.1.68:

     ```
pip install --upgrade pip
     sudo ln -s /path/to/cuda /usr/local/cuda-11.1
     pip install --upgrade jax==0.1.68 jaxlib==0.1.67+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

-result of installation: 

`Successfully installed jax-0.1.68 jaxlib-0.1.67+cuda111`

- run lqr_jax_MPC.py and get ImportError:
 
```
Traceback (most recent call last):
  File "/home/control/Documents/Carla projects/Carla_iLQR_MPC/MPC/ilqr_jax_MPC.py", line 1, in <module>
    from jax import jit, jacfwd, jacrev, hessian, lax
  File "/home/control/.local/lib/python3.7/site-packages/jax/__init__.py", line 16, in <module>
    from .api import (
  File "/home/control/.local/lib/python3.7/site-packages/jax/api.py", line 38, in <module>
    from . import core
  File "/home/control/.local/lib/python3.7/site-packages/jax/core.py", line 30, in <module>
    from . import dtypes
  File "/home/control/.local/lib/python3.7/site-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/home/control/.local/lib/python3.7/site-packages/jax/lib/__init__.py", line 51, in <module>
    from jaxlib import pytree
ImportError: cannot import name 'pytree' from 'jaxlib' (/home/control/.local/lib/python3.7/site-packages/jaxlib/__init__.py)
```

I have tried to install jaxlib from source but not succeed, it came up with this problem: https://stackoverflow.com/questions/70324228/how-to-deal-with-error-infinite-symlink-expansion-detected-in-building-jax-from

Also tried to install jaxlib and jax==0.2.14, 0.2.16 with pip and the lqr_jax_MPC.py still shows different Errors.

Do you know how to deal with them?

Many thanks.
